---
- name: Check if EPEL repo is already configured.
  stat:
    path: "{{ epel_repofile_path }}"
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"


- name: Ensure dependencies are installed.
  yum:
    name: "centos-release-gluster7"
    state: present

- name: Ensure Gluster packages are installed.
  yum:
    name:
      - glusterfs-client
    state: present


- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
    - "/var/www"

- name: Ensure Gluster volume is mounted.
  mount:
    name: "/var/www"
    src: "db1,db2,db3:gluster"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
