# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :server => {
    :box_name => "centos/7",
    :net => [
               {ip: "192.168.10.10", netmask: "255.255.255.0", adapter: 2, virtualbox__intnet: "private-net"},
            ]
  },

}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "512"]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

        case boxname.to_s
        when "server"
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "./provision.yml"
          end
#          box.vm.provision "shell", run: "always", inline: <<-SHELL
#            yum install -y epel-release
#            yum install -y openvpn iperf3 mc easy-rsa
#            setenforce 0
#          SHELL

        end

    end
  end
#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "v"
#    ansible.playbook = "provision/provision.yml"
#  end
end


