# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "centos/7",
    :net => [
               {adapter: 2, virtualbox__intnet: "bonding-net"},
               {adapter: 3, virtualbox__intnet: "bonding-net"},
            ]
  },

  :centralRouter => {
    :box_name => "centos/7",
    :net => [
               {adapter: 2, virtualbox__intnet: "bonding-net"},
               {adapter: 3, virtualbox__intnet: "bonding-net"},
               {adapter: 4, virtualbox__intnet: "central-net"},
            ]
  },

  :officeRouter => {
    :box_name => "centos/7",
    :net => [
               {adapter: 2, virtualbox__intnet: "test-net"},
               {adapter: 3, virtualbox__intnet: "test-net"},
               {adapter: 4, virtualbox__intnet: "central-net"},
            ]
  },

  :testClient1 => {
    :box_name => "centos/7",
    :net => [
               {adapter: 2, virtualbox__intnet: "test-net"},
            ]
  },
  :testServer1 => {
    :box_name => "centos/7",
    :net => [
               {adapter: 2, virtualbox__intnet: "test-net"},
            ]
  },

  :testClient2 => {
    :box_name => "centos/7",
    :net => [
               {adapter: 2, virtualbox__intnet: "test-net"},
            ]
  },
  :testServer2 => {
    :box_name => "centos/7",
    :net => [
               {adapter: 2, virtualbox__intnet: "test-net"},
            ]
  },

}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "256"]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

#        case boxname.to_s
#        when "inetRouter"
#          box.vm.provision "ansible" do |ansible|
#            ansible.playbook = "./provision/bond.yml"
#          end
#
#        when "centralRouter"
#          box.vm.provision "ansible" do |ansible|
#            ansible.playbook = "./provision/centralrouter.yml"
#          end
#
#        when "officeRouter"
#          box.vm.provision "ansible" do |ansible|
#            ansible.playbook = "./provision/inetrouter.yml"
#          end
#
#        when "testClient1"
#          box.vm.provision "ansible" do |ansible|
#            ansible.playbook = "./provision/vlan.yml"
#          end
#        when "testServer1"
#          box.vm.provision "ansible" do |ansible|
#            ansible.playbook = "./provision/vlan.yml"
#          end
#        when "testClient2"
#          box.vm.provision "ansible" do |ansible|
#            ansible.playbook = "./provision/vlan.yml"
#          end
#        when "testServer2"
#          box.vm.provision "ansible" do |ansible|
#            ansible.playbook = "./provision/vlan.yml"
#          end
#        end

    end
  end
  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "v"
    ansible.playbook = "provision/provision.yml"
  end
end


