Vagrant.configure(2) do |config|

  config.vm.define "web" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname="web"
    subconfig.vm.network :private_network, ip: "192.168.50.11"
    subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

  config.vm.define "log" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname="log"
    subconfig.vm.network :private_network, ip: "192.168.50.12"
    subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end


  config.ssh.insert_key = false 
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end

end
