# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.hostname = "dweb"
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.11.100"
    config.vm.define "dweb"
    config.vm.provider :virtualbox do |vb|
	vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    config.vm.provision "ansible" do |ansible|
	ansible.compatibility_mode = "2.0"
	ansible.playbook = "provision/provision.yml"
	ansible.become = "true"
    end

end
