---
- name: настройка сервера borgbackup
  hosts: server
  become: true
  roles:
    - role: server

- name: Настройка клиента borg
  hosts: client
  become: true
  roles:
    - role: client
#  vars:
#    mysql_pwd: "password"
#    wp_pwd: "wppass"
#    exp_pwd: "expass"
