MACHINES = {
  :"server" => {
    :box_name => "centos/7",
    :ip_addr => "192.168.11.100",
    :memory => "1024",
  },
  :"client" => {
    :box_name => "centos/7",
    :ip_addr => "192.168.11.101",
    :memory => "512",
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider "virtualbox" do |vb|
              vb.name = boxname.to_s 
              vb.memory = boxconfig[:memory]  
          end

          box.vm.provision "shell", inline: <<-SHELL
              mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
              sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
              systemctl restart sshd
              yum install -y nfs-utils rpcbind net-tools mc
          SHELL
      case boxname.to_s
      when "server"
           box.vm.provision "shell", run: "always", inline: <<-SHELL
               cp /vagrant/nfs /etc/sysconfig/nfs
               mkdir -p /export/share/upload
               chmod 777 /export/share/upload
               echo "/export/share *(rw,sync,no_root_squash,no_all_squash)" > /etc/exports

               systemctl enable --now rpcbind nfs-server nfs-lock nfs-idmap firewalld

               firewall-cmd --permanent --zone=public --add-service=nfs3
               firewall-cmd --permanent --zone=public --add-service=mountd
               firewall-cmd --permanent --zone=public --add-service=rpc-bind
               firewall-cmd --permanent --add-port=662/udp
               firewall-cmd --permanent --add-port=662/tcp
               firewall-cmd --permanent --add-port=892/udp
               firewall-cmd --permanent --add-port=892/tcp
               firewall-cmd --permanent --add-port=2020/udp
               firewall-cmd --permanent --add-port=32769/udp
               firewall-cmd --permanent --add-port=32803/tcp
               firewall-cmd --reload

           SHELL
       when "client"
           box.vm.provision "shell", run: "always", inline: <<-SHELL  
               echo "192.168.11.100:/export/share  /mnt  nfs vers=3,udp,noexec,nosuid 0 0"  >>/etc/fstab
               systemctl enable --now rpcbind nfs nfs-lock nfs-idmap firewalld
               mount /mnt
           SHELL
     end
   end
 end
end
