---
- name: Download WordPress
  get_url: 
    url: http://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress into /var/www/html
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    copy: no
  become: yes

- name: Chown nginx /var/www/html/wordpress
  file:
    path: /var/www/html/wordpress
    owner: nginx
    group: nginx
    recurse: yes
  become: yes

- name: Copy sample config file
  copy:
    src: wp-config.php
    dest: /var/www/html/wordpress/wp-config.php
    owner: nginx
    group: nginx
    mode: 0644

